### ISSUE TITLE
[BUG] Overscale in Android JB and ICS Easter Eggs with 1080p phone screen

### ISSUE THREAD

**Issue by tretdm** [hushenghao/AndroidEasterEggs#256]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.5.0 (from F-Droid)

### Bug description / Bug 描述

With standard phone screen metrics (1080 x 1920, 401dpi = xxhdpi) objects that are too large are displayed, as in the original medium-sized objects are displayed. This can be easily seen in the text below (Android Jelly Bean easter egg) and in the Nyandroid object animation (Android Ice Cream Sandwich easter egg). 

_The problem was also noticed in the original implementation with exactly the same screen resolution._

<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/e0c64042-ff78-4d8c-9475-710891b2e874" height="500"/>
<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/6572483e-766f-442b-99fa-a2590a43b77d" height="500" />

<p>

**720 x 1280 vs. 1080 x 1920**

<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/77c1689a-3dea-4619-a954-91ca65be0c23" height="500" />
<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/395630c5-8454-4359-b8fc-33d3a00ee7da" height="500" />

It would be nice if these easter eggs were adapted for high resolution (higher than 720 x 1280) or would you suggest manual scaling adjustment.

### Expected behavior / 预期行为

Found in Android ICS & JB easter eggs (including system).

### Actual behavior / 实际行为

Overscaled in some easter eggs.

### Steps to reproduce / 复现步骤

1. Open the app
2. Open BeanBag (click to show Android version) and/or Nyandroid (hold for a few seconds)

### UI / OS

AOSP

### Android Version / Android 版本

6

**Comment by hushenghao** [comment]
文本显示大小是受一些魔法数字来控制，我不会尝试修改它，不过我会处理文本换行不居中的问题

**Comment by tretdm** [comment]
But the problem is not so much in the text, but rather in the objects that were involved in the easter eggs.

**Comment by hushenghao** [comment]
As for the object scaling problem, I don't see any problem in the screenshots, they are just scaled according to different dpi, which is a problem on almost all Android Views.

**Comment by tretdm** [comment]
xxhdpi vs. xhdpi (screen resolution is also the same)
<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/49a6f2d2-2e7a-438d-8bc0-e02d7797e293" height="500" />
<img src="https://github.com/hushenghao/AndroidEasterEggs/assets/76806170/b0b9950f-81e3-45fc-8f29-b1ac7475935e" height="500" />

**Comment by hushenghao** [comment]
I found the reason for this problem because there is no limit on the size of the ImageView, The image size will be scaled according to the device screen density.
* JB: https://github.com/hushenghao/AndroidEasterEggs/blob/f8f6381b9cb646af886df147f927a26206360478/eggs/JellyBean/src/main/java/com/android_j/egg/BeanBag.java#L288-L294
* ICS: https://github.com/hushenghao/AndroidEasterEggs/blob/f8f6381b9cb646af886df147f927a26206360478/eggs/IceCreamSandwich/src/main/java/com/android_i/egg/Nyandroid.java#L116-L125

I fixed the targetDensity of BitmapDrawable to 480 to solve this problem.

commit: 39ce917107362c8dc41f13fb24a6666aa5ea29c4

* ICS: https://github.com/hushenghao/AndroidEasterEggs/blob/39ce917107362c8dc41f13fb24a6666aa5ea29c4/eggs/IceCreamSandwich/src/main/java/com/android_i/egg/Nyandroid.java#L133-L139
* JB:
https://github.com/hushenghao/AndroidEasterEggs/blob/39ce917107362c8dc41f13fb24a6666aa5ea29c4/eggs/JellyBean/src/main/java/com/android_j/egg/BeanBag.java#L155-L156

**Comment by tretdm** [comment]
Thanks!
