### ISSUE TITLE
[BUG] Android Kitkat charging screensaver does not cover the full screen

### ISSUE THREAD

**Issue by Aleksszz** [hushenghao/AndroidEasterEggs#349]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.6.3

### Bug description / Bug 描述

Android 4.4 Kitkat Easter Egg Screensaver does not cover the full screen, creating a very unpleasing black bezel

### Expected behavior / 预期行为

The screensaver covering the full screen

### Actual behavior / 实际行为

Screensaver covers 80% of the screen creating a black bezel

### Steps to reproduce / 复现步骤

1. Open the Android Kitkat Easter Egg
2. In phone settings look for screen saver
3. Select Android Kitkat screensaver
4. Initiate screensaver
5. See the issue

### UI / OS

OneUI 5.1

### Android Version / Android 版本

13

### Additional info / 额外信息

I'm on Samsung S20 FE

**Comment by Aleksszz** [comment]
I want to add that the Android 4.1 screensaver isn't affected, and that my issue appeared after some update

**Comment by hushenghao** [comment]
In the Android 4.4 Dessert Case, each dessert element is a square, but the screen proportions of today's devices are no longer satisfied with fixed proportions, so there will always be an area that cannot be filled.

If in order to fill the black border area, the display area can only be scaled up and then cropped, similar to 'ImageView scaleType=centerCrop', but this will cause a problem, the edge of the element may not be displayed completely.

**Comment by NurMiApp** [comment]
Update name is "[BUG] Android 4.4 charging screensaver does not cover this full screen" is coming.

*Product by NurBot a user this @Aleksszz.*

**Comment by hushenghao** [comment]
Fixed on v3.1.0-beta02
