### ISSUE TITLE
Easter egg Marshmellow land bag. 

### ISSUE THREAD

**Issue by Artermakov** [hushenghao/AndroidEasterEggs#387]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

Version 3.0.1

### Bug description / Bug 描述

On top there is a plus that adds several players. If you spawn only 1 android, then its color is normal. And if you spawn several, they will be the same color. For example, if you spawn the maximum number of androids, they will all be gray. If you spawn 2 androids, they will be the same color as the second android. 

### Expected behavior / 预期行为

All androids will be in different colors. 

### Actual behavior / 实际行为

They became the same color. 

### Steps to reproduce / 复现步骤

Spawn a few androids and see their color. 

### UI / OS

Emui 8.2.0

### Android Version / Android 版本

8.1.0

**Comment by hushenghao** [comment]
Each player's color is generated in order, and the purpose of this is to have different colors for different players, since most of the time players are added consecutively. 

https://github.com/hushenghao/AndroidEasterEggs/blob/1c82f4cd5efa5870e7e7337d340f8fd591d4db5b/eggs/Marshmallow/src/main/java/com/android_m/egg/MLand.java#L1042-L1051

https://github.com/hushenghao/AndroidEasterEggs/blob/1c82f4cd5efa5870e7e7337d340f8fd591d4db5b/eggs/Marshmallow/src/main/java/com/android_m/egg/MLand.java#L1115

The color is the same only when multiple additions and deletions are made to a player.
But I don't think that's a bug.

**Comment by hushenghao** [comment]
Fixed, Update new Beta version
